# 训练配置
train:
  device: 'cuda'
  batch_size: 32
  num_epochs: 100
  num_workers: 4

# 模型配置
model:
  input_dim: 9  # 位置(3) + 旋转(3) + 尺寸(3)
  hidden_dim: 256
  latent_dim: 128
  num_layers: 3

# 优化器配置
optimizer:
  learning_rate: 0.001
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.0001

# 数据配置
data:
  root: 'data/processed'
  room_types: ['bedroom']
  max_parts: 80

# 优化参数
optimization:
  overlap_weight: 10.0  # 重叠损失权重
  rel_weight: 1.0  # 相对属性损失权重 