name: scene-synthesis
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.9.0
  - torchvision
  - cudatoolkit=11.1
  - pytorch-lightning=1.4.9
  - numpy
  - scipy
  - h5py
  - tqdm
  - matplotlib
  - wandb
  - pip
  - pip:
    - hydra-core==1.1.1
    - omegaconf
    - open3d 