config:
  dataset:
    root: D:/cxcy2/LEGO-Net-main/sy2/data/processed
    room_types:
    - bedroom
    max_parts: 80
    train_split: 0.8
    val_split: 0.1
    batch_size: 32
    num_workers: 0
  vae:
    latent_dim: 256
    abs_dim: 10
    max_parts: 80
    num_class: 20
    weight_kld: 0.1
  optimizer:
    learning_rate: 0.001
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.0001
  train:
    max_epochs: 100
    learning_rate: 0.001
    device: cpu
    checkpoint_dir: checkpoints
    log_interval: 100
  optimization:
    num_steps: 200
    overlap_weight: 10.0
    rel_weight: 5.0
    min_distance: 0.3
    position_range: 4.0
    size_min: 0.3
    size_max: 3.0
    pos_noise_level: 0.1
    ang_noise_level: 0.26179939
    denoise_within_floorplan: true
    denoise_no_penetration: true
    denoise_weigh_by_class: true
  model:
    latent_dim: 256
    hidden_dim: 512
  gat:
    dropout: 0.1
    alpha: 0.2
    hidden_dim: 256
  rel_predictor:
    hidden_dims:
    - 256
    - 128
    dropout: 0.1
  test:
    checkpoint: checkpoints/lego_final.ckpt
    output_dir: results/test_results
  logging:
    project: Scene-Synthesis
    log_dir: logs
    wandb: false
